"""initial_schema

Revision ID: d6c8569ee456
Revises: 
Create Date: 2026-04-18 15:47:39.346204
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6c8569ee456'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('version_string', sa.String(length=30), nullable=False),
    sa.Column('build_number', sa.Integer(), nullable=False),
    sa.Column('changelog', sa.JSON(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('rollout_percent', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('min_supported_version', sa.String(length=30), nullable=True),
    sa.Column('store_url_ios', sa.Text(), nullable=True),
    sa.Column('store_url_android', sa.Text(), nullable=True),
    sa.Column('published_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('beta_cohort_members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cohort_key', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.String(length=191), nullable=False),
    sa.Column('country_code', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cohort_key', 'user_id', name='uq_beta_cohort_members_cohort_user')
    )
    op.create_index(op.f('ix_beta_cohort_members_cohort_key'), 'beta_cohort_members', ['cohort_key'], unique=False)
    op.create_index(op.f('ix_beta_cohort_members_user_id'), 'beta_cohort_members', ['user_id'], unique=False)
    op.create_table('beta_metrics_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=191), nullable=False),
    sa.Column('window_days', sa.Integer(), nullable=False),
    sa.Column('activation_progress_pct', sa.Integer(), nullable=False),
    sa.Column('first_3_nights_completed', sa.Integer(), nullable=False),
    sa.Column('first_3_nights_total', sa.Integer(), nullable=False),
    sa.Column('command_total_7d', sa.Integer(), nullable=False),
    sa.Column('command_completion_rate_pct', sa.Integer(), nullable=False),
    sa.Column('wind_down_sessions_7d', sa.Integer(), nullable=False),
    sa.Column('nightly_feedback_total', sa.Integer(), nullable=False),
    sa.Column('nightly_feedback_helpful_pct', sa.Integer(), nullable=False),
    sa.Column('cohort_status_line', sa.Text(), nullable=False),
    sa.Column('quality_gate_line', sa.Text(), nullable=False),
    sa.Column('generated_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_beta_metrics_snapshots_user_id'), 'beta_metrics_snapshots', ['user_id'], unique=True)
    op.create_table('feature_flags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('flag_key', sa.String(length=80), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('enabled_globally', sa.Boolean(), nullable=False),
    sa.Column('enabled_for_plans', sa.JSON(), nullable=False),
    sa.Column('rollout_percent', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_flags_flag_key'), 'feature_flags', ['flag_key'], unique=True)
    op.create_table('firmware_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version_string', sa.String(length=30), nullable=False),
    sa.Column('changelog', sa.JSON(), nullable=False),
    sa.Column('download_url', sa.Text(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('rollout_percent', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('target_device_ids', sa.JSON(), nullable=False),
    sa.Column('published_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('first_three_nights_progress',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=191), nullable=False),
    sa.Column('signup_completed_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_scene_preview_completed_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_automation_completed_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_winddown_completed_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timeline_review_completed_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_first_three_nights_progress_user_id'), 'first_three_nights_progress', ['user_id'], unique=True)
    op.create_table('mobile_auth_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=191), nullable=False),
    sa.Column('client_name', sa.String(length=80), nullable=False),
    sa.Column('access_token', sa.String(length=255), nullable=False),
    sa.Column('refresh_token', sa.String(length=255), nullable=False),
    sa.Column('issued_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('access_expires_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('refresh_expires_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('revoked_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mobile_auth_sessions_access_token'), 'mobile_auth_sessions', ['access_token'], unique=True)
    op.create_index(op.f('ix_mobile_auth_sessions_refresh_token'), 'mobile_auth_sessions', ['refresh_token'], unique=True)
    op.create_index(op.f('ix_mobile_auth_sessions_user_id'), 'mobile_auth_sessions', ['user_id'], unique=False)
    op.create_table('mobile_command_feedback',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=191), nullable=False),
    sa.Column('command_id', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('vote', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('trace_id', sa.String(length=100), nullable=True),
    sa.Column('voted_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'command_id', name='uq_mobile_command_feedback_user_command')
    )
    op.create_index(op.f('ix_mobile_command_feedback_command_id'), 'mobile_command_feedback', ['command_id'], unique=False)
    op.create_index(op.f('ix_mobile_command_feedback_user_id'), 'mobile_command_feedback', ['user_id'], unique=False)
    op.create_table('mobile_command_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=191), nullable=False),
    sa.Column('command_id', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('event_summary', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('trace_id', sa.String(length=100), nullable=True),
    sa.Column('command_created_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('command_updated_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('command_completed_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mobile_command_records_command_id'), 'mobile_command_records', ['command_id'], unique=True)
    op.create_index(op.f('ix_mobile_command_records_user_id'), 'mobile_command_records', ['user_id'], unique=False)
    op.create_table('nightly_summary_feedback_progress',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=191), nullable=False),
    sa.Column('helpful_count', sa.Integer(), nullable=False),
    sa.Column('not_helpful_count', sa.Integer(), nullable=False),
    sa.Column('last_vote', sa.String(length=20), nullable=True),
    sa.Column('last_vote_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_summary_generated_at_utc', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nightly_summary_feedback_progress_user_id'), 'nightly_summary_feedback_progress', ['user_id'], unique=True)
    op.create_table('user_feature_overrides',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=191), nullable=False),
    sa.Column('flag_key', sa.String(length=80), nullable=False),
    sa.Column('override_value', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('set_by', sa.String(length=255), nullable=True),
    sa.Column('set_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'flag_key', name='uq_user_feature_overrides_user_flag')
    )
    op.create_index(op.f('ix_user_feature_overrides_flag_key'), 'user_feature_overrides', ['flag_key'], unique=False)
    op.create_index(op.f('ix_user_feature_overrides_user_id'), 'user_feature_overrides', ['user_id'], unique=False)
    op.create_index('idx_events_type_timestamp', 'events', ['event_type', 'timestamp'], unique=False)
    op.create_index('idx_events_user_timestamp', 'events', ['user_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_timestamp'), 'events', ['timestamp'], unique=False)
    op.create_index('idx_sleep_sessions_user_date', 'sleep_sessions', ['user_id', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_sleep_sessions_user_date', table_name='sleep_sessions')
    op.drop_index(op.f('ix_events_timestamp'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_index('idx_events_user_timestamp', table_name='events')
    op.drop_index('idx_events_type_timestamp', table_name='events')
    op.drop_index(op.f('ix_user_feature_overrides_user_id'), table_name='user_feature_overrides')
    op.drop_index(op.f('ix_user_feature_overrides_flag_key'), table_name='user_feature_overrides')
    op.drop_table('user_feature_overrides')
    op.drop_index(op.f('ix_nightly_summary_feedback_progress_user_id'), table_name='nightly_summary_feedback_progress')
    op.drop_table('nightly_summary_feedback_progress')
    op.drop_index(op.f('ix_mobile_command_records_user_id'), table_name='mobile_command_records')
    op.drop_index(op.f('ix_mobile_command_records_command_id'), table_name='mobile_command_records')
    op.drop_table('mobile_command_records')
    op.drop_index(op.f('ix_mobile_command_feedback_user_id'), table_name='mobile_command_feedback')
    op.drop_index(op.f('ix_mobile_command_feedback_command_id'), table_name='mobile_command_feedback')
    op.drop_table('mobile_command_feedback')
    op.drop_index(op.f('ix_mobile_auth_sessions_user_id'), table_name='mobile_auth_sessions')
    op.drop_index(op.f('ix_mobile_auth_sessions_refresh_token'), table_name='mobile_auth_sessions')
    op.drop_index(op.f('ix_mobile_auth_sessions_access_token'), table_name='mobile_auth_sessions')
    op.drop_table('mobile_auth_sessions')
    op.drop_index(op.f('ix_first_three_nights_progress_user_id'), table_name='first_three_nights_progress')
    op.drop_table('first_three_nights_progress')
    op.drop_table('firmware_versions')
    op.drop_index(op.f('ix_feature_flags_flag_key'), table_name='feature_flags')
    op.drop_table('feature_flags')
    op.drop_index(op.f('ix_beta_metrics_snapshots_user_id'), table_name='beta_metrics_snapshots')
    op.drop_table('beta_metrics_snapshots')
    op.drop_index(op.f('ix_beta_cohort_members_user_id'), table_name='beta_cohort_members')
    op.drop_index(op.f('ix_beta_cohort_members_cohort_key'), table_name='beta_cohort_members')
    op.drop_table('beta_cohort_members')
    op.drop_table('app_versions')
    # ### end Alembic commands ###
