"""add_memory_push_subscription_tables

Revision ID: d7f43a4871f4
Revises: d6c8569ee456
Create Date: 2026-04-18 15:49:31.934236
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7f43a4871f4'
down_revision: Union[str, None] = 'd6c8569ee456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=191), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('interval', sa.String(length=20), nullable=False),
    sa.Column('payment_provider', sa.String(length=40), nullable=False),
    sa.Column('price_kwd', sa.Float(), nullable=False),
    sa.Column('provider_subscription_id', sa.String(length=255), nullable=False),
    sa.Column('provider_plan_id', sa.String(length=255), nullable=False),
    sa.Column('provider_status', sa.String(length=60), nullable=False),
    sa.Column('next_renewal_at', sa.String(length=40), nullable=False),
    sa.Column('grace_end_at', sa.String(length=40), nullable=False),
    sa.Column('started_at', sa.String(length=40), nullable=False),
    sa.Column('last_payment_at', sa.String(length=40), nullable=False),
    sa.Column('cancelled_at', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_records_user_id'), 'subscription_records', ['user_id'], unique=True)
    op.create_table('user_daily_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=191), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('summary', sa.String(length=220), nullable=False),
    sa.Column('stress_level', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_daily_events_user_ts', 'user_daily_events', ['user_id', 'ts'], unique=False)
    op.create_index(op.f('ix_user_daily_events_ts'), 'user_daily_events', ['ts'], unique=False)
    op.create_index(op.f('ix_user_daily_events_user_id'), 'user_daily_events', ['user_id'], unique=False)
    op.create_table('user_memory_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=191), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_text', sa.Text(), nullable=False),
    sa.Column('assistant_text', sa.Text(), nullable=False),
    sa.Column('emotion', sa.String(length=40), nullable=False),
    sa.Column('personality', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_memory_entries_user_ts', 'user_memory_entries', ['user_id', 'ts'], unique=False)
    op.create_index(op.f('ix_user_memory_entries_ts'), 'user_memory_entries', ['ts'], unique=False)
    op.create_index(op.f('ix_user_memory_entries_user_id'), 'user_memory_entries', ['user_id'], unique=False)
    op.create_table('user_push_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=191), nullable=False),
    sa.Column('expo_token', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_push_tokens_user_id'), 'user_push_tokens', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_push_tokens_user_id'), table_name='user_push_tokens')
    op.drop_table('user_push_tokens')
    op.drop_index(op.f('ix_user_memory_entries_user_id'), table_name='user_memory_entries')
    op.drop_index(op.f('ix_user_memory_entries_ts'), table_name='user_memory_entries')
    op.drop_index('idx_memory_entries_user_ts', table_name='user_memory_entries')
    op.drop_table('user_memory_entries')
    op.drop_index(op.f('ix_user_daily_events_user_id'), table_name='user_daily_events')
    op.drop_index(op.f('ix_user_daily_events_ts'), table_name='user_daily_events')
    op.drop_index('idx_daily_events_user_ts', table_name='user_daily_events')
    op.drop_table('user_daily_events')
    op.drop_index(op.f('ix_subscription_records_user_id'), table_name='subscription_records')
    op.drop_table('subscription_records')
    # ### end Alembic commands ###
