// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeayP9i_SMjhBroMBp92osOwNh9JUmgtA',
    appId: '1:727106830062:web:4b8d0df4a3afe3cbb7bdff',
    messagingSenderId: '727106830062',
    projectId: 'smart-bed-2da03',
    authDomain: 'smart-bed-2da03.firebaseapp.com',
    databaseURL: 'https://smart-bed-2da03-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-bed-2da03.firebasestorage.app',
    measurementId: 'G-VKZQVQWCSQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw9hzpLco7iyqN3zAueP1KQt1nVrWupLk',
    appId: '1:727106830062:android:09f0706fdc4d53e5b7bdff',
    messagingSenderId: '727106830062',
    projectId: 'smart-bed-2da03',
    databaseURL: 'https://smart-bed-2da03-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-bed-2da03.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhjjl-4v7KFa6r0-FIzW2piIACkZLulBU',
    appId: '1:727106830062:ios:074007459fcc2c3fb7bdff',
    messagingSenderId: '727106830062',
    projectId: 'smart-bed-2da03',
    databaseURL: 'https://smart-bed-2da03-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-bed-2da03.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeayP9i_SMjhBroMBp92osOwNh9JUmgtA',
    appId: '1:727106830062:web:bab443ade5b20c5db7bdff',
    messagingSenderId: '727106830062',
    projectId: 'smart-bed-2da03',
    authDomain: 'smart-bed-2da03.firebaseapp.com',
    databaseURL: 'https://smart-bed-2da03-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-bed-2da03.firebasestorage.app',
    measurementId: 'G-4KLB6NK30C',
  );
}
